### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by Huanle** [mahulchak/svmu#2]
Hi There,

I ran into this error when execting svmu.
svmu ref.vs.sample.mm.delta ref.fa sample.fa  3
''
A little bit information about my linux platform:

Configured with: ../gcc-5.2.0/configure --prefix=/opt/Modules/gcc/5.2.0 --disable-multilib
Thread model: posix
gcc version 5.2.0 (GCC)

Linux delta040 2.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 21:19:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Hoepfully, you can show me a way to fix it.

Thanks a lot.

Elzed

**Comment by mahulchak** [comment]
Hi,
Could you please provide me the following information -
1. exact error
2. could you please run it again with /usr/bin/time -v
i.e.
 /usr/bin/time -v svmu ref.vs.sample.mm.delta ref.fa sample.fa 3
this will help me figure out if it is a memory issue. How big are your reference and sample sequences?
-Mahul

**Comment by Huanle** [comment]
Hi Mahul,

Thanks for your prompt response.

What i got from running ' time svmu pun.vs.TOX.mm.delta pun.reformat.fa TOX.reformat.fa 4 '
is 

"Segmentation fault
real    0m4.404s
user    0m4.092s
sys     0m0.143s
"

**Comment by mahulchak** [comment]
Please run
/usr/bin/time -v svmu
And not
time svmu
Also, could you please tell me your sequence sizes ?

**Comment by Huanle** [comment]
$ /usr/bin/time  svmu pun.vs.TOX.mm.delta pun.reformat.fa TOX.reformat.fa 4

0.42user 1.77system 0:02.33elapsed 94%CPU (0avgtext+0avgdata 680668maxresident)k
0inputs+8outputs (21major+170236minor)pagefaults 0swaps

sequence size:
TOX: 386,148,524 
pun: 191,018,889

**Comment by mahulchak** [comment]
How much memory does your system have ?

**Comment by mahulchak** [comment]
Okay. I'll push some updates on github tomorrow. Try that and let me know
if you get the segfault.

**Comment by BoWang12** [comment]
Hello, I ran svmu using my data, and I give it 300G memory, it was generating 'trans.txt' file, then got the segmentation fault error:
/var/spool/p6444/bnbhimem2/job_scripts/19840053: line 3: 37489 Segmentation fault      ~/software/svmu/svmu ../split.job/sample.2ref.mm.delta ../ref.fa ../sample.fa 5
Could you give some suggestions? Thanks.

**Comment by mahulchak** [comment]
Could you please run svmu with
/usr/bin/time -v

So that I know how much memory was being used when it crashed.

**Comment by BoWang12** [comment]
Here is what I got using  /usr/bin/time -v : 

Command terminated by signal 11
	Command being timed: "/sonas-hs/hpc/home/software/svmu/svmu ../split.job/sample.2ref.mm.delta ../ref.fa ../sample.fa 5"
	User time (seconds): 704.88
	System time (seconds): 23.49
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 12:10.15
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 132863040
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 6296558
	Voluntary context switches: 59
	Involuntary context switches: 78007
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0

**Comment by mahulchak** [comment]
Hmm. And you said it created the trans.txt file but didn't write anything
to it? Did it create any other file?

**Comment by BoWang12** [comment]
Yes, it created 'trans.txt', and this file is not empty, have some results inside, but no other files created

**Comment by mahulchak** [comment]
Will you be able to share your delta file ?

**Comment by BoWang12** [comment]
Yes, it was a small file, which I used to test svmu

[sample.2ref.mm.delta.txt](https://github.com/mahulchak/svmu/files/1559298/sample.2ref.mm.delta.txt)

**Comment by mahulchak** [comment]
@Huanle I have pushed some new updates. Could you please check if it works now?

**Comment by BoWang12** [comment]
Thanks for yoru help, I just tried the new updates, unfortunately seems still not working, here is what I got:
Command terminated by signal 11
	Command being timed: "/sonas-hs/hpc/home/bwang/software/svmu/svmu ./sample.2ref.mm.delta ../ref.fa ./sample 5"
	User time (seconds): 426.95
	System time (seconds): 14.75
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 7:22.45
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 91573440
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 3715444
	Voluntary context switches: 24
	Involuntary context switches: 45528
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0

**Comment by BoWang12** [comment]
I'm sharing my data files with you through dropbox, could you test on your side? see how it goes. Thanks. Here is the link: https://www.dropbox.com/sh/23ewo64ykicj8un/AADKhyLRjCHxr4wmZ_fNYFJwa?dl=0

**Comment by BoWang12** [comment]
Hello, I was wondering have you figured out the problem? Thanks.

**Comment by mahulchak** [comment]
@BoWang12 sorry for the delay. The problem should now be solved.

**Comment by situssog** [comment]
Hello Mahul,

I'm also trying to run the package but I'm getting the same problem. It runs, produces part of the trans file, and stops with the message: Segmentation fault (core dumped)

the command:
/usr/bin/time -v svmu svmu_ref.delta Ref.fasta sample.fasta 10

Command terminated by signal 11
        Command being timed: "svmu svmu_ref.delta Ref.fasta sample.fasta 10"
        User time (seconds): 76.08
        System time (seconds): 2.69
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:18.99
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 4447332
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 1215104
        Voluntary context switches: 58
        Involuntary context switches: 48888
        Swaps: 0
        File system inputs: 0
        File system outputs: 56
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0

I'm wondering if this is a compilation problem or if this is a general problem others are having.
My input files are here:
https://www.dropbox.com/sh/0bljkelodsxfuju/AADfXfX9iGULk-VCQPhSbjJna?dl=0

Thanks a lot for your help,

/S

**Comment by mahulchak** [comment]
@situssog Thanks for letting me know and sharing the files. I will take a look.

**Comment by mahulchak** [comment]
@situssog I am unable to replicate your error. You'll need 4Gb RAM to run this. It's also possible that you don't have the latest version. I will commit some changes today or tomorrow and then you can check it again.

**Comment by situssog** [comment]
Hello Mahul,

Thanks a lot for your quick reply. 
I allocated 24 Gb to the job in the cluster. After trying several things I notice the problem was the name of the sequences in the sample.fasta file (apparently too long). Is there a max number of characters in the seq name? Is tehre a way to change these settings? 

After changing names to a very simple one (For instance to >ABCD) the package runs.

Now, my output files do not show mitochondrial SVs. Is this because of the length of the sequence? Can I change something in the MUMmer run to get them? 

Thanks a lot for your help,

/S

**Comment by situssog** [comment]
Hello Mahul,
Sorry for the multiple consecutive messages. Now I notice that if I reduce the n parameter (from 5 to 2 or even 1/0), I do get the MT SV. However, this is always not the case and in some cases, I don't get SV from large chromosomes. Link to input files as example:

https://www.dropbox.com/sh/0bljkelodsxfuju/AADfXfX9iGULk-VCQPhSbjJna?dl=0

This a link to the alignment of that sample and the reference:  
http://qb.cshl.edu/assemblytics/interactive_dotplot.php?code=aYmv37WbPdJ9MMZn6uVK&nickname=my_favorite_organism

If I run MUMmer using the -mumreference parameter, I get more chromosomes, but for instance chromosome III only shows one out of two contigs. 

Thanks a lot again,

/S

**Comment by mahulchak** [comment]
@situssog I am sorry but I am unable to replicate any of the errors you are mentioning. I have updated the code with some new commits. Please check if they solve the issues you are having. I looked for all reference chromosomes in sv.txt and found all of them. The commands I have used :
```
nucmer -maxmatch -noextend Ref.fasta sample.fasta 
/usr/bin/time -v ./svmu sample2ref.delta ref.fasta sample.fasta 1 l
```
l is a new parameter. Please see svmu updated README for its description.
